- src/components/Navigation.jsx
- src/pages/Board.jsx
- src/pages/BoardDetail.jsx
board :  ranking 컴포넌트, nav바 연결 , 하트수정,
board_detail : 초기 구현
> board, detail

- public/data/rank.json
- src/components/Name.jsx
- src/components/Navigation.jsx
- src/components/Ranking.jsx
- src/pages/GetStarted.jsx
- src/pages/MainPage.jsx
- src/pages/NotFound.jsx
- 네비게이션바 아이콘 클릭시 navigate 설정 : 프로필이랑 보드는 완성하면 할 예정
- 랭킹보드 : x축 margin 수정해야함
그 랭킹보드 컴포넌트에 
`<span className="font-undong font-bold">Ranking</span>`
이런식으로 카드리스트 위쪽에 바로 붙여놨어요!
Board에서
<h2 className="px-6 text-xl font-bold">Ranking</h2>
이거 지우고 사용해도 될 거 같아요! 밑에 Recipe도 post.json으로 목업 데이터 만들어서
컴포넌트로 사용하면 좋을거 같아요~ 제가 내일 post.json에 만들까요?
> 2.12 네비게이션, 메인페이지, 랭킹보드, NotFound 페이지 수정

- src/App.js
- src/components/Logo.jsx
- src/components/Navigation.jsx
- src/pages/LogIn.jsx
- src/pages/NotFound.jsx
- src/pages/ResetPassword.jsx
- src/pages/SignUp.jsx
- 로그인 페이지 기초 디자인 (데이터 통신은 아직)
- 비밀번호 재설정 페이지, 회원가입 페이지와 navigate로 연결
> [feat] 로그인 페이지 기초디자인, 회원가입, 비번 재설정 라우팅

- src/components/Logo.jsx
- src/components/Name.jsx
- src/pages/GetStarted.jsx
- src/pages/MainPage.jsx
- tailwind.config.js
> [fix]시작화면, 홈화면의 버튼 hover:text-black 적용

- src/components/Name.jsx
- src/components/Ranking.jsx
- src/pages/LogIn.jsx
- src/pages/MainPage.jsx
> [feat] 로그인 페이지 기본 스타일링 완료, 메인페이지 문자열 위치 수정

- src/pages/LogIn.jsx
- src/pages/ResetPassword.jsx
- tailwind.config.js
> [feat] 비밀번호 재설정 페이지 기본 디자인 완료, 로그인 페이지 일부 수정

- src/pages/LogIn.jsx
- src/pages/ResetPassword.jsx
- src/pages/SignUp.jsx
2.18
제곧내
프론트단에서 처리해야할 UI 기능만 마무리하면 회원가입, 비밀번호 재설정은 끝
SNS 로그인을 해결해야 함
> 회원가입 페이지, 비밀번호 재설정 페이지 디자인 거의 완성

- src/pages/LogIn.jsx
- src/pages/ResetPassword.jsx
- src/pages/SignUp.jsx
> [feat] 이메일 유효성 검사 추가

- src/components/Ranking.jsx
- src/pages/GetStarted.jsx
- src/pages/MainPage.jsx
> 초기화면, 메인화면 버튼 딜레이 수정 & div 태그를 시멘틱 태그로 변경

- public/index.html
- src/App.js
- src/apis/auth.js
- src/components/Navigation.jsx
- src/context/LoginContext.jsx
- src/pages/LogIn.jsx
- src/pages/SignUp.jsx
> [feat] 로그인 컨텍스트 수정

- src/context/LoginContext.jsx
- src/index.js
- src/pages/DeleteAccount.jsx
- src/pages/SignUp.jsx
> [feat] 로그인 컨텍스트 수정, 회원탈퇴 페이지 생성

- src/components/User.jsx
- src/pages/DeleteAccount.jsx
> [feat] 회원정보 수정, 회원탙뢰를 위한 User 컴포넌트 생성. 회원탈퇴 페이지 DeleteAccount 생성

- src/components/Kakao.jsx
- src/components/Navigation.jsx
- src/components/User.jsx
- src/index.js
- src/pages/ManageAccount.jsx
- src/pages/NotFound.jsx
- src/pages/SignUp.jsx
2.24
- KaKao : 카카오 auth
- ManageAccount : 회원정보 수정과 회원탈퇴를 할 수 있는 페이지 (의논 필요)
- DeleteAccount : 회원탈퇴 페이지
> [feat] 회원가입 페이지 수정, 카카오 로그인 컴포넌트 생성

- src/apis/auth.js
- src/context/LoginContext.jsx
- src/index.js
- src/pages/LogIn.jsx
- src/pages/ResetPassword.jsx
- src/pages/SignUp.jsx
> [feat] 로그인 auth 파일 수정

- package.json
> [feat] package.json에 프록시 설정 추가

- src/context/LoginContext.jsx
> [feat] axios post 설정 변경

- src/context/User.jsx
- src/pages/ResetPassword.jsx
- src/pages/SignUp.jsx
> [feat] 회원가입, 로그인, 비밀번호 재설정 페이지 수정

- src/components/SnsLogin.jsx
- src/index.css
- src/pages/LogIn.jsx
> [feat] root에 overflow-y:scroll 설정, 비밀번호 재설정 페이지 수정

- src/context/User.jsx
- src/index.js
- src/pages/DeleteUser.jsx
- src/pages/ResetPassword.jsx
- src/pages/SignUp.jsx
> [feat] 회원가입, 비밀번호 재설정 인증요청에 emailType 추가하여 구분. 회원탈퇴, 로그아웃 구현

- src/pages/Mypage.jsx
> [feat] 회원 탈퇴, 로그아웃 버튼 추가

- src/context/User.jsx
- src/pages/ResetPassword.jsx
- src/pages/SignUp.jsx
> [feat] User.jsx에서 인증요청, 인증확인 구현. 회원가입, 비밀번호 재설정 페이지 수정

- public/index.html
index.html에서 
<link rel="manifest" href="%PUBLIC_URL%/manifest.json" />의 rel을 "/manifest"로 추가했더니 해결
> [feat] manifest.json 콘솔 오류 메세지 해결

- src/index.js
- src/pages/BoardDetail.jsx
- src/pages/GptHistory.jsx
- src/pages/GptResult.jsx
- src/pages/GptSearch.jsx
- src/pages/Mypage.jsx
- src/pages/UploadBoard.jsx
- gpt검색결과 전 로딩화면 수정,
- gpt 검색결과 화면 구현 - api미연결
- mypage 정보 api연결준비
> [feat] loading, gpthistory , mypage api

- package-lock.json
- package.json
- src/index.js
- src/pages/Board.jsx
- src/pages/BoardDetail.jsx
- src/pages/GptHistory.jsx
- src/pages/GptHistory_Detail.jsx
- src/pages/GptResult.jsx
- src/pages/GptSearch.jsx
- src/pages/Mypage.jsx
> [feat] GPT search, result, history 

- src/index.js
- src/pages/Board.jsx
- src/pages/EditPost.jsx
- src/pages/GptResult.jsx
- src/pages/GptSearch.jsx
- src/pages/MainPage.jsx
- src/pages/Mypage.jsx
- gpt search, result api 변경
- gpt saved, detail 연결완료
- mypage 나의 레시피 api연결완료
- mypage 나의 레시피 삭제완료
- board 페이징 코드수정
> [feat] gpt, mypage 3/15 연결

- package-lock.json
- package.json
- src/pages/GptResult.jsx
- src/pages/GptSavedDetail.jsx
- src/pages/GptSavedList.jsx
- src/pages/GptSearch.jsx
- src/pages/Mypage.jsx
$ npm install --save react-toastify
> [feat] gpt error toastify적용

- src/components/Navigation.jsx
- src/pages/BoardDetail.jsx
- src/pages/GptSavedList.jsx
- src/pages/GptSearch.jsx
GptSearch , GptSavedList 에 수정하였습니다
> [feat] user.nickName수정 

- src/pages/Board.jsx
- src/pages/BoardDetail.jsx
- src/pages/EditPost.jsx
- src/pages/Mypage.jsx
- src/pages/UploadBoard.jsx
- board에서 미로그인시 하트 클릭안되고 숫자안올라가도록 
- uploadboard 글 새로 작성 완료했을때 상세페이지로 
- boardDetail 서버로 like 요청 
- 페이지네이션 역순해결,  - 테스트 필요
> [feat]테스트 후 반영, board 페이지네이션, toggleLike, uploadboard, boardDetail like수정

- src/pages/Board.jsx
- src/pages/BoardDetail.jsx
- src/pages/GptResult.jsx
- src/pages/GptSavedList.jsx
- src/pages/Mypage.jsx
- mypage 내가작성한페이지, 내가 좋아요누른 페이지 페이지네이션 구분
- 검색결과 페이지네이션 2개 보이는 문제  —근데 일시적인건지 테스트 필요
- boardDetail  ↔ board  fetchlikedposts 호출
- gpt 저장할때 accesstoken검사
> [feat] board like , mypage 수정

- src/App.js
- src/components/ui/Navigation.jsx
- src/index.js
- src/pages/Board.jsx
- src/pages/BoardDetail.jsx
- src/pages/EditPost.jsx
- src/pages/EditProfile.jsx
- src/pages/GetStarted.jsx
- src/pages/GptResult.jsx
- src/pages/GptSavedDetail.jsx
- src/pages/GptSavedList.jsx
- src/pages/MainPage.jsx
- src/pages/Mypage.jsx
- src/pages/ProtectedRoute.jsx
- src/pages/UploadBoard.jsx
- 시작 화면 하단 센터에 카피라이트 문구 추가
- Navigation.jsx를 컴포넌트 디렉토리의 ui 하위로 이동
> [feat]Protected Route 업데이트, 카피라이트 문구 추가, 네비게이션 ui 하위로 이동

- src/components/BoardDetail/BoardDetailMain.jsx
- src/components/ui/BackButton.jsx
- src/components/ui/Navigation.jsx
- src/pages/Board.jsx
- src/pages/BoardDetail.jsx
- src/pages/GptResult.jsx
- src/pages/GptSavedDetail.jsx
- src/pages/UploadBoard.jsx
- boardDetail 리액트쿼리 적용
- navigation, backbtn 메모이제이션
-  SEO-시맨틱 태그로 변경
- 게시물 업로드 입력값 확인
> [fix] boardDetail 리액트쿼리,  메모이제이션,SEO-시맨틱 태그

- src/components/Board/RecipeCard.jsx
- src/components/Board/SearchBar.jsx
- src/components/Ranking/RankingList.jsx
- src/components/common/ScrollToTopButton.jsx
- src/context/UserContext.jsx
- src/pages/Board/Board.jsx
- src/pages/Board/BoardDetail.jsx
- src/pages/Board/EditPost.jsx
- src/pages/Board/UploadPost.jsx
- src/pages/GPTs/GptResult.jsx
- src/pages/GPTs/GptSavedDetail.jsx
- src/pages/GPTs/GptSavedList.jsx
- src/pages/GPTs/GptSearch.jsx
- src/pages/User/DeleteUser.jsx
- src/pages/User/EditProfile.jsx
- src/pages/User/LoginSuccess.jsx
- src/pages/User/Mypage.jsx
- src/pages/User/SignIn.jsx
- src/utils/customedError.js
handleError를 UserContext.jsx에서 cutomError.js로 이동<br/>
GptSavedList의 네브바 width를 w-[31rem]으로 수정하여 정상적인 모습으로 수정
> [Refactor] handleError 위치 변경, GptSavedList 네브바 수정
